"""init

Revision ID: 2971eaca5c7f
Revises: 
Create Date: 2025-03-28 09:19:34.666330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2971eaca5c7f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bet',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('event_uuid', sa.UUID(), nullable=True),
    sa.Column('amount', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('in_progress', 'win', 'loss', name='betstatusenum'), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bet')
    # ### end Alembic commands ###
