"""init

Revision ID: 8af2685f1482
Revises: 
Create Date: 2025-04-01 05:37:09.635637

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8af2685f1482'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bet',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('event_uuid', sa.UUID(), nullable=False),
    sa.Column('event_status', sa.Enum('in_progress', 'win', 'loss', name='eventstatusenum'), nullable=False),
    sa.CheckConstraint('amount > 0', name='positive_amount'),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bet')
    # ### end Alembic commands ###
