services:
  bet-marker:
    build:
      context: ../..
      dockerfile: envs/dev/Dockerfile
    ports:
      - '8001:8000'
    env_file:
      - .env
    volumes:
      - ../../app:/betting/app
    restart: unless-stopped
    networks:
      - betting

  postgres:
    image: mirror.gcr.io/postgres:16.2
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - betting

volumes:
  postgres:

networks:
  betting:
    external: true
